### ISSUE TITLE
Publish getting failed

### ISSUE THREAD

**Issue by KPrasad17** [WebVella/WebVella-ERP#192] opened 2023-06-12 12:30 UTC
I am getting the error while deploying the publish. i am not getting any of the error while running the application

![image](https://github.com/WebVella/WebVella-ERP/assets/134255214/736541bb-ced0-464f-ae5d-0d8c70fcd420)

**Comment by 28106830** [comment] 2023-08-14 13:29
I also encountered the same problem. This file cannot be renamed, and there was an error when renaming it

If you change the directory name, there will be too many changes

**Comment by 28106830** [comment] 2023-08-16 05:36
Looking forward to resolving the issue

**Comment by bzashev** [comment] 2023-08-16 06:55
Hey, sorry for the late answer. 
This is not an issue of the platform but a recent change Microsoft made and it has an easy fix. Check this thread
https://stackoverflow.com/questions/69919664/publish-error-found-multiple-publish-output-files-with-the-same-relative-path

**Comment by 28106830** [comment] 2023-08-17 09:03
1. This file is not a document and must be output (you provided a regular file conflict)

2. This file needs to be used during runtime after actual publication, so all subsequent directories need to use this file. Therefore, using SDK or WEB will cause another file to be unavailable

3. I can place the same files from two libraries in different directories, such as the SDK in the Page directory and the Web in the root directory, which can solve the problem, but this is not the standard solution

**Comment by rumen-yankov** [comment] 2023-08-19 12:56
Hey guys,  the problem is easy solved by using configuration setting bellow in project file.  Some people get an error, others not and this is related to problem with Microsoft changes and updates.

<PropertyGroup>
	
	<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
</PropertyGroup>

**Closed by rumen-yankov** 2023-08-19 12:56 UTC
